import React, { useState } from 'react';
import { ChevronDown, ChevronUp, FileText, BarChart2 } from 'lucide-react';

const ResponseViewer = ({ message }) => {
  const [expanded, setExpanded] = useState(false);

  if (!message || message.error) return null;

  return (
    <div className="bg-white rounded-xl shadow-lg border overflow-hidden">
      <button
        onClick={() => setExpanded(!expanded)}
        className="w-full px-6 py-4 flex items-center justify-between hover:bg-gray-50 transition-colors"
      >
        <div className="flex items-center space-x-3">
          <BarChart2 className="h-5 w-5 text-purple-600" />
          <span className="font-medium">Response Analysis</span>
        </div>
        {expanded ? (
          <ChevronUp className="h-5 w-5 text-gray-500" />
        ) : (
          <ChevronDown className="h-5 w-5 text-gray-500" />
        )}
      </button>

      {expanded && (
        <div className="px-6 py-4 border-t bg-gray-50">
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-4">
            <div className="bg-blue-50 p-3 rounded-lg">
              <div className="text-sm text-blue-600 font-medium">Analyzer Phase</div>
              <div className="text-xs text-blue-800 mt-1">
                Intent identification & requirement analysis
              </div>
            </div>
            <div className="bg-green-50 p-3 rounded-lg">
              <div className="text-sm text-green-600 font-medium">Generator Phase</div>
              <div className="text-xs text-green-800 mt-1">
                Solution generation & response creation
              </div>
            </div>
            <div className="bg-purple-50 p-3 rounded-lg">
              <div className="text-sm text-purple-600 font-medium">Evaluator Phase</div>
              <div className="text-xs text-purple-800 mt-1">
                Quality check & refinement
              </div>
            </div>
          </div>

          <div className="space-y-2">
            <div className="flex items-center space-x-2 text-sm text-gray-600">
              <FileText className="h-4 w-4" />
              <span>Response generated by 3 AI agents working in sequence</span>
            </div>
            <div className="text-xs text-gray-500">
              Timestamp: {new Date(message.timestamp).toLocaleString()}
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default ResponseViewer;